// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mnzrsmbtlsmmrbdrwafh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1uenJzbWJ0bHNtbXJiZHJ3YWZoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk3Mzc0ODUsImV4cCI6MjA2NTMxMzQ4NX0.TRXlAtIWy8-Di6QwWQ6rXbpXmTuD_KiybrlTsL7HgjM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);